package dev.solora.navigation

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.TextView
import android.widget.Toast
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.lifecycle.lifecycleScope
import androidx.navigation.fragment.findNavController
import dev.solora.R
import dev.solora.quotes.QuotesViewModel
import kotlinx.coroutines.launch

class QuoteDetailFragment : Fragment() {
    private val quotesViewModel: QuotesViewModel by viewModels()
    
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        return inflater.inflate(R.layout.fragment_quote_detail, container, false)
    }
    
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        
        val tvReference = view.findViewById<TextView>(R.id.tv_reference)
        val tvSummary = view.findViewById<TextView>(R.id.tv_summary)
        val btnExportPdf = view.findViewById<Button>(R.id.btn_export_pdf)
        val btnShare = view.findViewById<Button>(R.id.btn_share)
        
        val quoteId = requireArguments().getLong("id", 0L)
        
        // Observe the specific quote
        viewLifecycleOwner.lifecycleScope.launch {
            quotesViewModel.quoteById(quoteId).collect { quote ->
                if (quote != null) {
                    tvReference.text = "Quote ${quote.reference}"
                    
                    val detailedSummary = buildString {
                        appendLine("📋 CLIENT INFORMATION")
                        appendLine("Client: ${quote.clientName}")
                        appendLine("Address: ${quote.address}")
                        appendLine()
                        
                        appendLine("⚡ ENERGY DETAILS")
                        quote.monthlyUsageKwh?.let { appendLine("Monthly Usage: ${String.format("%.1f", it)} kWh") }
                        quote.monthlyBillRands?.let { appendLine("Average Bill: R${String.format("%.2f", it)}") }
                        appendLine("Tariff Rate: R${String.format("%.2f", quote.tariff)}/kWh")
                        appendLine()
                        
                        appendLine("🌞 SOLAR SYSTEM DESIGN")
                        appendLine("Panel Rating: ${quote.panelWatt}W each")
                        appendLine("Number of Panels: ${quote.panels}")
                        appendLine("System Size: ${String.format("%.2f", quote.systemKw)} kW")
                        appendLine("Inverter Size: ${String.format("%.2f", quote.inverterKw)} kW")
                        appendLine("Sun Hours: ${String.format("%.1f", quote.sunHours)} hours/day")
                        appendLine()
                        
                        appendLine("💰 FINANCIAL BENEFITS")
                        appendLine("Monthly Savings: R${String.format("%.2f", quote.savingsRands)}")
                        appendLine("Annual Savings: R${String.format("%.2f", quote.savingsRands * 12)}")
                        appendLine()
                        
                        appendLine("📅 Quote Generated: ${java.text.SimpleDateFormat("dd MMM yyyy, HH:mm", java.util.Locale.getDefault()).format(java.util.Date(quote.dateEpoch))}")
                    }
                    
                    tvSummary.text = detailedSummary
                } else {
                    tvReference.text = "Quote Not Found"
                    tvSummary.text = "The requested quote could not be loaded. It may have been deleted or doesn't exist."
                }
            }
        }
        
        // Handle export button (for now just shows success message)
        btnExportPdf.setOnClickListener {
            Toast.makeText(requireContext(), "PDF export functionality coming soon!", Toast.LENGTH_SHORT).show()
        }
        
        // Handle share button
        btnShare.setOnClickListener {
            quotesViewModel.quoteById(quoteId).value?.let { quote ->
                val shareText = "Solar Quote for ${quote.clientName}\n\n" +
                        "System Size: ${String.format("%.2f", quote.systemKw)} kW\n" +
                        "Panels: ${quote.panels} x ${quote.panelWatt}W\n" +
                        "Monthly Savings: R${String.format("%.2f", quote.savingsRands)}\n" +
                        "Annual Savings: R${String.format("%.2f", quote.savingsRands * 12)}\n\n" +
                        "Generated by Solora Solar Solutions"
                
                val shareIntent = android.content.Intent().apply {
                    action = android.content.Intent.ACTION_SEND
                    type = "text/plain"
                    putExtra(android.content.Intent.EXTRA_TEXT, shareText)
                    putExtra(android.content.Intent.EXTRA_SUBJECT, "Solar Quote - ${quote.reference}")
                }
                startActivity(android.content.Intent.createChooser(shareIntent, "Share Quote"))
            } ?: run {
                Toast.makeText(requireContext(), "Quote not available for sharing", Toast.LENGTH_SHORT).show()
            }
        }
    }
}


